export const games = [
    {
      id: 1,
      imgs: [
        "https://i.postimg.cc/6q97FbCJ/zombie-Cover-Banner.png",
        "https://i.postimg.cc/9f9NbKjx/screen1-2.png",
        "https://i.postimg.cc/y88DFC0H/Screen2.png",
        "https://i.postimg.cc/L6ndfyhW/Screen3.png",
      ],
      title: "Survival Game.",
      desc: [
        "Welcome to world of Zombie Apocalypse, an immersive 3D survival game developed using Unity. This game delivers a experience as you fight hordes of relentless zombies to stay alive!",
        "Here I utilize the classic keyboard controls (WASD) for smooth movement, allowing you to navigate your way through treacherous environments with ease.",
        "To Aim wield your weapon with precision using the mouse, allowing for accurate targeting and shoots against zombies, possibily all monsters have a chance to spawn a med kit to hell your life.",
        "At the certain point will respawn a boss, and the difficulty is increased.",
      ],
      link: "https://tempestdeveloper.itch.io/apocalipse-zombie-v120",
    },
    {
      id: 2,
      imgs: [
        "https://i.postimg.cc/HLwhM0YJ/Banner-Merlin.png",
        "https://i.postimg.cc/FsCH6M1j/Captura-de-tela-2024-05-01-010028.png",
        "https://i.postimg.cc/cHL7sqMd/Captura-de-tela-2024-04-17-123659.png",
        "https://i.postimg.cc/x1qcT0Bx/Captura-de-tela-2024-05-03-114954.png",
        "https://i.postimg.cc/jdcs7Gyp/Merlin.png",
      ],
      title: "Multiplayer FPS Game",
      desc: [
        "I've made a new project to implement multiplayer functionality using Unity for my small FPS game called Merlin: Arcane Warfare.",
        " I was really surprised at how quickly I set up using Netcode, lobby, and relay packages. I've synchronized the animations between the client and server sides, as well as the movement of the player, the projectiles you can shoot, and the environment.",
        "Since I create the server and the way to connect locally, I start to search at unity docs how to handle to use a P2P way to connect at any computer.",
        "In the finals I got a code to join in the host session and the players can share to others join the room, it's amazing multiplayer setup!",
      ],
      link: "https://tempestdeveloper.itch.io/merlin",
    },
    {
      id: 3,
      imgs: [
        "https://i.postimg.cc/bJ1Hdqwr/Port-cookhell.png",
        "https://i.postimg.cc/C5SCj6Ff/print-Cook-Hell.png",
        "https://i.postimg.cc/1XhmTpkP/CookHell.png",
        "https://i.postimg.cc/N0Cxvx73/print2-Over.png",
        "https://i.postimg.cc/0y0BtsVf/Cook-Hell-Itch-Page.gif",
      ],
      title: "Cooking Game.",
      desc: [
        "I started this project with the idea of creating a 3D game in Unity, aiming to develop a full demo similar to the commercial cooking game Overcooked.",
        "After six months of learning how to handle objects, instantiate them, and transfer them between game objects (like catching ingredients, placing them on tables or plates, and changing the state of the food), I began to encounter problems with my code.",
        "When I realized I couldn't continue with my existing code, I started researching design patterns and discovered events and delegates in C#. This significantly improved my code. By using scriptable objects to manage data, I was able to finish the project.",
      ],
      link: "https://tempestdeveloper.itch.io/cook-hell",
    },
    {
      id: 4,
      imgs: [
        "https://i.postimg.cc/QdLDt9nV/buble4.png",
        "https://i.postimg.cc/hjk2Fj4V/Bubble-Guy.gif",
        "https://i.postimg.cc/DfGGj69W/Bubble-Guy-bubblestages.gif",
        "https://i.postimg.cc/vmK2GXHR/Bubble-Guy-bubblejump.gif",
        "https://i.postimg.cc/9MxdckQC/Bubble-Guy-bubbledash.gif",
      ],
      title: "Game made in 10 days for 99Jam",
      desc: [
        'This game is completely inspired by Celeste developed using Unity. The Legend of Bubble Guy was made for 99Jam in 10 days. With the theme of "Take a Deep Breath," we started to think about how the character could gain new mechanics around this concept.',
        'In this game, the player is able to inflate their bubble to stage 1 and utilize the "Jump" bubble to navigate by jumping from one bubble to another.',
        'Progress further by inflating your bubble from stage 1 to stage 2, unlocking the ability to use the "Dash" bubble, which allows you to enter other bubbles.',
      ],
      link: "https://tempestdeveloper.itch.io/bubbleguy",
    },
    {
      id: 5,
      imgs: [
        "https://i.postimg.cc/prt7vzdt/first-Cover-Img.png",
        "https://i.postimg.cc/L61pwCR1/s1.jpg",
        "https://i.postimg.cc/VNGsmJhr/s2.jpg",
        "https://i.postimg.cc/jjFTBGWy/s3.jpg",
        "https://i.postimg.cc/NfpzNR2H/s4.jpg",
      ],
      title: "Platform 2D game.",
      desc: [
        "This platformer game was developed in Unity to master handling obstacles, collectibles, and scene transitions.",
        "The project aimed to enhance skills in game design and programming, providing a comprehensive learning experience in creating engaging and dynamic gameplay elements.",
        "Through this development process, key techniques in collision detection, object interaction, and level design were explored and implemented.",
      ],
      link: "https://tempestdeveloper.itch.io/first-one",
    },
    {
      id: 6,
      imgs: [
        "https://i.postimg.cc/Y0LzBDrH/highlight.gif",
        "https://i.postimg.cc/L8ZvgM1D/Captura-de-tela-2024-05-10-133739.png",
        "https://i.postimg.cc/05df7frg/Captura-de-tela-2024-05-11-225626.png",
        "https://i.postimg.cc/Y0LzBDrH/highlight.gif",
      ],
      title: "Unity Asset tool still in development",
      desc: [
        "I aim to make this tool available on the Unity Store very soon, and it will likely help other game developers create open worlds more quickly.",
        "What the tool can do right now: Create vertices for terrain; Generate terrain shapes procedurally; Spawn tree prefabs around the terrain procedurally.",
        "What I want to implement: Change the border of the terrain, make rounded; Add water around the island (I need to conduct some research to determine whether I should use another asset pack for water shaders or if I'll need to create them myself); Implement pathfinding for rivers inside the terrain; Check Optimizing; Create intuitive GUI layout to handle inside the editor.",
        "I'm still working on my asset tool for unity, striving to enhance performance by reducing the number of materials and draw calls. I'm not entirely certain if it's satisfactory yet, but for now, it's acceptable.",
      ],
      link: "#",
    },
  ];
