export const products = [
  {
    id: 1,
    imgs: ["https://i.postimg.cc/Y0LzBDrH/highlight.gif"],
    title: "Unity Asset tool",
    desc: "Unity Asset tool: World procedural Generator, still in development, more coming soon...",
    link: "",
  },
  {
    id: 2,
    imgs: ["https://i.postimg.cc/YC1W1dwD/merlin.png"],
    title: "(Multiplayer) Merlin: Arcane Warfare",
    desc: "Multiplayer game called Merlin: Arcane Warfare",
    link: "https://tempestdeveloper.itch.io/merlin",
  },
  {
    id: 3,
    imgs: ["https://i.postimg.cc/bJ1Hdqwr/Port-cookhell.png"],
    title: "CookHell",
    desc: "Coooooooook heell :D",
    link: "https://tempestdeveloper.itch.io/cook-hell",
  },
  {
    id: 4,
    imgs: ["https://i.postimg.cc/QdLDt9nV/buble4.png"],
    title: "The Legend of Bubble Guy",
    desc: "The Legend of Bubble Guy is a 2D game made for the 99 Jam",
    link: "https://tempestdeveloper.itch.io/bubbleguy",
  },
  {
    id: 5,
    imgs: ["https://i.postimg.cc/6q97FbCJ/zombie-Cover-Banner.png"],
    title: "Zombie Apocalypse.",
    desc: "Zombie Apocalypse. 3D Survival Game.",
    link: "https://tempestdeveloper.itch.io/apocalypse-zombie-v120",
  },
  {
    id: 6,
    imgs: ["https://i.postimg.cc/4xrYXxp1/print2.png"],
    title: "Unity Components. 8 Mini Games inside of one Project.",
    desc: "Unity Components. 8 Mini Games inside of one Project with Unity.",
    link: "https://tempestdeveloper.itch.io/unity-components",
  },
  {
    id: 7,
    imgs: [
      "https://i.postimg.cc/prt7vzdt/first-Cover-Img.png"
    ],
    title: "First one, platform 2D game.",
    desc: "First one, platform 2D game.",
    link: "https://tempestdeveloper.itch.io/first-one",
  },
];

export const awards = [
  {
    id: 1,
    title: "Unity 2D part 1: Creating a 2D game",
    img: "https://i.postimg.cc/2ytmz70y/cert1.png",
    desc: "Throughout this course, I acquired the skills to craft my very own 2D game using Unity.",
    link: "https://cursos.alura.com.br/certificate/5587efc6-6e9e-4be3-9f64-70ebfcbf80c2",
  },
  {
    id: 2,
    title: "Unity part 1: create of a survival zombie game for Web",
    img: "https://i.postimg.cc/44cTtV26/cert1.png",
    desc: "Alura courses offer an immersive learning experience in which you can harness the power of Unity and C# to master the art of creating your own survival game.",
    link: "https://cursos.alura.com.br/certificate/47e0eb66-4d2b-44d3-9ea1-ac1307861297",
  },
  {
    id: 3,
    title: "Unity part 2: Illumination, interface and good practices",
    img: "https://i.postimg.cc/kX13Ps2d/cert1.png",
    desc: "In this course, I focused on improving visual elements, refining user interfaces, and mastering essential game development practices within Unity.",
    link: "https://cursos.alura.com.br/certificate/54b66172-8ee9-4b58-a2c0-0ef4e4afbfbf",
  },
  {
    id: 4,
    title: "Unity part 3: Creating a boss and polishing the game",
    img: "https://i.postimg.cc/nr1sh562/cert1.png",
    desc: "This course provide to me a good knowledge, learning how to create challenging boss battles and fine-tune my game for a polished finish.",
    link: "https://cursos.alura.com.br/certificate/0a40a400-cec4-4e99-a049-003fcfc2d368",
  },
  {
    id: 5,
    title: "Javascript ES6 essentials",
    img: "https://i.postimg.cc/nzfhnvJg/award.jpg",
    desc: "JavaScript ES6 essential is a free online course for beginners learn JavaScript basics for web.",
    link: "https://www.dio.me/certificate/9A6EAF56",
  },
  {
    id: 6,
    title: "Introduction to Git and GitHub",
    img: "https://i.postimg.cc/Nj0SyMGZ/git.jpg",
    desc: "Introduction to Git and GitHub is a free online course to learn Git and GitHub code version control.",
    link: "https://www.dio.me/certificate/97E7F74F",
  },
  {
    id: 7,
    title: "Introduction to make websites with HTML5 and CSS3",
    img: "https://i.postimg.cc/Px6dwcsM/html5-css3.jpg",
    desc: "Introduction to make websites with HTML5 and CSS3 is a free online course to learn how to make websites.",
    link: "https://www.dio.me/certificate/9FD15C79",
  },
  {
    id: 8,
    title: "JavaScript Certified",
    img: "https://i.postimg.cc/t4015xPK/Certificado-Java-Script.jpg",
    desc: "JavaScript Certified is a free online course to learn how to use javascript for web.",
    link: "https://programacaoweb.com.br",
  },
  {
    id: 9,
    title: "PHP Certified",
    img: "https://i.postimg.cc/BQPLHg85/Certificado-PHP.jpg",
    desc: "PHP basic course is a free online course to learn PHP basics for web.",
    link: "https://programacaoweb.com.br",
  },
  {
    id: 10,
    title: "HTML Certified",
    img: "https://i.postimg.cc/CxjR6xsz/Certificado-HTML.jpg",
    desc: "HTML basics course is a free online course to learn make structure pages for web.",
    link: "https://programacaoweb.com.br",
  },
  {
    id: 11,
    title: "CSS Certified",
    img: "https://i.postimg.cc/vTk4C1K6/Certificado-CSS.jpg",
    desc: "CSS is a free online course to learn change style in pages for web.",
    link: "https://programacaoweb.com.br",
  },
  {
    id: 12,
    title: "Bootstrap 5 Certified",
    img: "https://i.postimg.cc/gjnwMygW/Certificado-Bootstrap-5.jpg",
    desc: "Bootstrap 5 is a free online course, to learn how to use bootstrap, css framework.",
    link: "https://programacaoweb.com.br",
  },
  {
    id: 13,
    title: "Jquery Certified",
    img: "https://i.postimg.cc/9XnwDSfF/Certificado-j-Query.jpg",
    desc: "Jquery certified is a free online course to learn Jquery library of javascript.",
    link: "https://programacaoweb.com.br",
  },
];
